name = "scope/scope"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
Conch = { wally = "alicesaidhi/conch", version = "^0.3.1" }
ConchUi = { wally = "alicesaidhi/conch-ui", version = "^0.3.1" }
Promise = { wally = "lukadev-0/typed-promise", version = "^4.0.2" }
Signal = { wally = "ffrostfall/luausignal", version = "^0.5.0" }
Vide = { wally = "cayasde/vide-opinionated", version = "^0.4.0" }
